apiVersion: v1
kind: Pod
metadata:
  name: nginx-example1
  labels:
    name: nginx-example1
spec:
  containers:
    - name: nginx-example1
      image: nginx:1.24
      resources:
        limits:
          memory: "64Mi"
          cpu: "0.2"
      ports:
        - containerPort: 80
